LIBPNGX_VERSION = v1.6.49
LIBPNGX_SITE = https://github.com/pnggroup/libpng.git
LIBPNGX_SITE_METHOD = git
LIBPNGX_LICENSE = BSD-3-Clause
LIBPNGX_LICENSE_FILES = LICENSE.md
LIBPNGX_INSTALL_STAGING = YES
LIBPNGX_INSTALL_TARGET = YES
LIBPNGX_DEPENDENCIES = libzlib

LIBPNGX_PROVIDES = libpng

$(eval $(cmake-package))
